sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
install:
  - npm install -g codecov
  - npm install
script:
  - 'grunt'
  - codecov
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/
