language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
  - '9'
  - '8'
install:
  - npm install -g codecov
  - npm install
after_success:
  - npm run codecov
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/
